### PR TITLE
let the user choose the date range with a datepicker.

### PR DESCRIPTION
**Pull request by amalrik**
This PR implements a datepicker, letting the user choose the date range.
In case no date is choose the default behavior is d-8 which is current searchjoy only option.

Here are some screenshots showing the result:
ss1
ss2
ss3
ss4

### CODE REVIEW

**Comment by ACPK** [comment]
@amalrik - This looks awesome!

**Comment by janklimo** [comment]
This looks handy @amalrik! @ankane any plans on merging this?

**Comment by ankane** [comment]
Hey @amalrik, thanks for the PR 👍 and really sorry it's taken so long to respond. Unfortunately, I don't want to add any more dependencies to Searchjoy right now.

**Comment by benreyn** [comment]
@ankane, I have an interest in picking this back up. Was the primary concern bringing in more dependencies? Would an approach that uses the date inputs that rails provides out of the box be preferable?

**Pull request closed without merging**
